// Usage of try-catch for error handling

let items;

items.forEach((item) => {
  console.log(item);
});
