// Usage of try-catch for error handling

let items;

items.forEach((item) => {
  console.log(item);
});

console.log("Error management is working correctly");

let info = "kodluyoruz";
console.log(info);
